

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChaosGui.java
 *
 * Created on Nov 3, 2012, 6:10:50 PM
 */
/**
 *
 * @author andzerb
 */
import ChaosGui3.Generator;
import org.math.plot.*;
import javax.swing.*;





public class Guigui extends javax.swing.JPanel {
    public int ISeedX = 0;
    public int ISeedY = 0;
    public double IDenominator = 1;
    public int IMaxpoints = 0;
     
    /** Creates new form ChaosGui */
    public Guigui() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PointsLabel = new javax.swing.JLabel();
        PointsSlider = new javax.swing.JSlider();
        Title = new javax.swing.JLabel();
        SeedX = new javax.swing.JTextField();
        SeedXLabel = new javax.swing.JLabel();
        SeedY = new javax.swing.JTextField();
        SeedYLabel = new javax.swing.JLabel();
        Generate = new javax.swing.JButton();
        Denominator = new javax.swing.JTextField();
        DenominatorLabel = new javax.swing.JLabel();
        Maxpoints = new javax.swing.JTextField();
        MaxpointsLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(800, 700));

        PointsLabel.setText("Points (100-100000)");

        PointsSlider.setMaximum(100000);
        PointsSlider.setMinimum(100);

        Title.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        Title.setText("The Chaos Game-Andrew Zerbe");

        SeedX.setText("0");
        SeedX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeedXActionPerformed(evt);
            }
        });

        SeedXLabel.setLabelFor(SeedX);
        SeedXLabel.setText("Seed X Value");

        SeedY.setText("0");
        SeedY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeedYActionPerformed(evt);
            }
        });

        SeedYLabel.setLabelFor(SeedY);
        SeedYLabel.setText("Seed Y Value");

        Generate.setText("Generate Fractal");
        Generate.setMaximumSize(new java.awt.Dimension(97, 97));
        Generate.setMinimumSize(new java.awt.Dimension(97, 97));
        Generate.setPreferredSize(new java.awt.Dimension(80, 80));
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });

        Denominator.setText("2");
        Denominator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenominatorActionPerformed(evt);
            }
        });

        DenominatorLabel.setText("Denominator");

        Maxpoints.setText("10000");
        Maxpoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxpointsActionPerformed(evt);
            }
        });

        MaxpointsLabel.setText("Points to gen.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(PointsSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PointsLabel))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Generate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(SeedX, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .add(18, 18, 18)
                                .add(SeedXLabel))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(SeedY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(SeedYLabel)))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(Maxpoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(MaxpointsLabel)
                                .add(130, 130, 130))
                            .add(layout.createSequentialGroup()
                                .add(Denominator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(DenominatorLabel)))))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .add(Title)
                .add(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(Title)
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PointsLabel)
                    .add(PointsSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SeedX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(SeedXLabel)
                    .add(Denominator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(DenominatorLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SeedY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(SeedYLabel)
                    .add(Maxpoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(MaxpointsLabel))
                .add(9, 9, 9)
                .add(Generate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void SeedXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeedXActionPerformed
    ISeedX = Integer.parseInt(SeedX.getText());
        System.out.println("SeedX: " + SeedX.getText());

}//GEN-LAST:event_SeedXActionPerformed

private void SeedYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeedYActionPerformed
    ISeedY = Integer.parseInt(SeedY.getText());
    System.out.println("Seedy: " + SeedY.getText());
}//GEN-LAST:event_SeedYActionPerformed

private void DenominatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenominatorActionPerformed
    IDenominator = Integer.parseInt(Denominator.getText());
        System.out.println("Denominator: " + Denominator.getText());

}//GEN-LAST:event_DenominatorActionPerformed

private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
    //Plot2DPanel print = Generator.generate(IMaxpoints, IDenominator, ISeedX, ISeedY);
    JFrame frame = new JFrame("Chaos Game");
    frame.setSize(600, 600);
    //frame.setContentPane(print);
    frame.setVisible(true);
    
}//GEN-LAST:event_GenerateActionPerformed

private void MaxpointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxpointsActionPerformed
    IMaxpoints = Integer.parseInt(Maxpoints.getText());
    System.out.println("Maxpoints: " + Maxpoints.getText());
    
}//GEN-LAST:event_MaxpointsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Denominator;
    private javax.swing.JLabel DenominatorLabel;
    private javax.swing.JButton Generate;
    private javax.swing.JTextField Maxpoints;
    private javax.swing.JLabel MaxpointsLabel;
    private javax.swing.JLabel PointsLabel;
    private javax.swing.JSlider PointsSlider;
    private javax.swing.JTextField SeedX;
    private javax.swing.JLabel SeedXLabel;
    private javax.swing.JTextField SeedY;
    private javax.swing.JLabel SeedYLabel;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
