/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mandelGui.java
 *
 * Created on Dec 8, 2012, 11:04:11 AM
 */
package mandelgui;

import java.awt.Component;
import org.math.plot.*;

/**
 *
 * @author andzerb
 */
public class mandelGui extends javax.swing.JFrame {
    public static Plot3DPanel wontwork = new Plot3DPanel();
    /** Creates new form mandelGui */
    public mandelGui() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        MandelorJulia = new javax.swing.JComboBox();
        learnMore = new javax.swing.JButton();
        Resolution = new javax.swing.JSlider();
        ResLabel = new javax.swing.JLabel();
        Cx = new javax.swing.JTextField();
        Cy = new javax.swing.JTextField();
        Cz = new javax.swing.JTextField();
        CValuesLabel = new javax.swing.JLabel();
        Power = new javax.swing.JTextField();
        PowerLabel = new javax.swing.JLabel();
        Generate = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        Title.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        Title.setText("The Mandelbulb: Andrew Zerbe");

        MandelorJulia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generate Mandelbulb", "Generate Juliabulb" }));
        MandelorJulia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MandelorJuliaActionPerformed(evt);
            }
        });

        learnMore.setText("Learn more");

        Resolution.setMinimum(7);
        Resolution.setMinorTickSpacing(1);
        Resolution.setAlignmentX(0.4F);

        ResLabel.setText("Resolution");

        Cx.setText("C X value");
        Cx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxActionPerformed(evt);
            }
        });

        Cy.setText("C Y value");

        Cz.setText("C Z value");

        CValuesLabel.setText("C values for Julia set");

        Power.setText("8");
        Power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerActionPerformed(evt);
            }
        });

        PowerLabel.setText("Power");

        Generate.setText("Generate!");
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });

        ErrorLabel.setText("No errors yet!");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(learnMore)
                            .add(layout.createSequentialGroup()
                                .add(MandelorJulia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(93, 93, 93)
                                .add(Cx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(Cy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(Cz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(37, 37, 37)
                        .add(Power, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(144, 144, 144)
                        .add(Title))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Generate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Resolution, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(19, 19, 19)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(ResLabel)
                                .add(83, 83, 83)
                                .add(CValuesLabel)
                                .add(80, 80, 80)
                                .add(PowerLabel))
                            .add(ErrorLabel))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(Title)
                .add(6, 6, 6)
                .add(learnMore)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(MandelorJulia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Cx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Cy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Cz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Power, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(ResLabel)
                        .add(CValuesLabel)
                        .add(PowerLabel))
                    .add(Resolution, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Generate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ErrorLabel))
                .add(786, 786, 786))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void MandelorJuliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MandelorJuliaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_MandelorJuliaActionPerformed

private void CxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CxActionPerformed

private void PowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_PowerActionPerformed

private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
    System.out.println(MandelorJulia.getSelectedItem());
    boolean DidItWork = true;
    if(MandelorJulia.getSelectedItem() == "Generate Mandelbulb"){ // Mandelbulb
        System.out.println("Generating mandel.");
        int powertext = 0;
        try{
            
            powertext = Integer.parseInt(Power.getText());
            
            
        }catch(java.lang.NumberFormatException e){
         System.out.println("That didn't work.");
         DidItWork = false;
            
        }
        final int pp=powertext;
        if(DidItWork == true){
            ErrorLabel.setText("Generating mandel with res " + (double)Resolution.getValue()/100 + " and power " + powertext);
            (new Thread(){
                public void run(){
                    Plot3DPanel mandelbulb = Mandelbulb.mandelGen((double)Resolution.getValue()/100, new TriplexNumbers(0,0,0), pp);
                    javax.swing.JFrame Mandelbulb= new javax.swing.JFrame("Mandelbulb");
                    Mandelbulb.setContentPane(mandelbulb);
                    Mandelbulb.setSize(700,700);
                    Mandelbulb.setVisible(true);
                }
            }).start();
        }else{
            ErrorLabel.setText("Please enter a real integer!");
            
        }
        
    }else{

        System.out.println("Generating julia.");
        int powertext = 0;
        int xtext = 0;
        int ytext = 0;
        int ztext = 0;
        try{
            
            powertext = Integer.parseInt(Power.getText());
            xtext = Integer.parseInt(Cx.getText());
            ytext = Integer.parseInt(Cy.getText());
            ztext = Integer.parseInt(Cz.getText());
            
            
        }catch(java.lang.NumberFormatException e){
         System.out.println("That didn't work.");
         DidItWork = false;
         System.out.println(DidItWork);
            
        }
        if(DidItWork = false){
          
            ErrorLabel.setText("Generating julia with res " + (double)Resolution.getValue()/100 + "with c value " + Cx.getText() + ", " + Cy.getText() + ", " + Cz.getText() + " and power " + powertext);
            Plot3DPanel Julia = Mandelbulb.juliaGen((double)Resolution.getValue()/100, new TriplexNumbers(0,0,0), powertext);
            javax.swing.JFrame julia= new javax.swing.JFrame("Juliabulb");
            julia.setContentPane(Julia);
            julia.setSize(700,700);
            julia.setVisible(true);
        }else{
            
            ErrorLabel.setText("Please enter a real integer!");
            
        }
        
    }
    DidItWork = true;
}//GEN-LAST:event_GenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mandelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mandelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mandelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mandelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                mandelGui gui = new mandelGui();
                gui.add(wontwork);
                gui.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CValuesLabel;
    private javax.swing.JTextField Cx;
    private javax.swing.JTextField Cy;
    private javax.swing.JTextField Cz;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton Generate;
    private javax.swing.JComboBox MandelorJulia;
    private javax.swing.JTextField Power;
    private javax.swing.JLabel PowerLabel;
    private javax.swing.JLabel ResLabel;
    private javax.swing.JSlider Resolution;
    private javax.swing.JLabel Title;
    private javax.swing.JButton learnMore;
    // End of variables declaration//GEN-END:variables
}
