/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChaosGui3.java
 *
 * Created on Nov 9, 2012, 7:14:40 PM
 */
package ChaosGui3;

import java.awt.Component;
import org.math.plot.*;
import javax.swing.JOptionPane;

       
/**
 *
 * @author andzerb
 */
public class ChaosGui3 extends javax.swing.JFrame {
    public int numChaos = 0;
    public double[] vX = {0.0, 1.5, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0} ;
    public double[] vY = {0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
    public int numVertices = 3;
    /** Creates new form ChaosGui3 */
    public ChaosGui3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Generate = new javax.swing.JButton();
        seedx = new javax.swing.JTextField();
        seedy = new javax.swing.JTextField();
        Denom = new javax.swing.JTextField();
        Maxpoints = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ChangeVertices = new javax.swing.JButton();
        Numer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Generate.setText("Generate");
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });

        seedx.setText("0");
        seedx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedxActionPerformed(evt);
            }
        });

        seedy.setText("0");
        seedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedyActionPerformed(evt);
            }
        });

        Denom.setText("2");

        Maxpoints.setText("3000");

        jLabel1.setText("Seed X");

        jLabel2.setText("Seed Y");

        jLabel3.setText("Denominator");

        jLabel4.setText("Points to generate");

        jLabel5.setText("Andrew Z-- Chaos Game");

        ChangeVertices.setText("Change Vertices");
        ChangeVertices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeVerticesActionPerformed(evt);
            }
        });

        Numer.setText("1");

        jLabel6.setText("Numerator");

        ErrorLabel.setText("No Errors Yet!");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Generate)
                            .add(ChangeVertices)
                            .add(layout.createSequentialGroup()
                                .add(Maxpoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel4)))
                        .addContainerGap())
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(Denom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .add(18, 18, 18)
                            .add(jLabel3)
                            .add(279, 279, 279))
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, seedy)
                                .add(seedx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(18, 18, 18)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel2)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabel5)
                                            .add(layout.createSequentialGroup()
                                                .add(jLabel1)
                                                .add(187, 187, 187)))))
                                .add(layout.createSequentialGroup()
                                    .add(121, 121, 121)
                                    .add(ErrorLabel)))
                            .add(136, 136, 136))
                        .add(layout.createSequentialGroup()
                            .add(Numer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .add(18, 18, 18)
                            .add(jLabel6)
                            .add(294, 294, 294)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(seedx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(seedy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2)))
                    .add(layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(ErrorLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Numer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Denom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Maxpoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ChangeVertices)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Generate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void seedxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_seedxActionPerformed

private void seedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedyActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_seedyActionPerformed

private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
    
    numChaos++;
    boolean DidItWork = true;
    Plot2DPanel panel = new Plot2DPanel();
    try{
        panel = (Generator.generate(Integer.parseInt(Maxpoints.getText()), Double.parseDouble(Numer.getText()),Double.parseDouble(Denom.getText()), Double.parseDouble(seedx.getText()), Double.parseDouble(seedy.getText()), vX, vY,numVertices ));
    }catch(java.lang.NumberFormatException e){
        
         ErrorLabel.setText("Not a number, you poop!");
         DidItWork = false;
        
    }catch(java.lang.ArrayIndexOutOfBoundsException f){
        ErrorLabel.setText("Messed up vertices, you poop!");
        DidItWork = false;
        
    }
    if(DidItWork == true){
        ErrorLabel.setText("Generated IFS.");
        System.out.println("Generated an IFS.");
        
        javax.swing.JFrame ChaosPanel = new javax.swing.JFrame("ChaAwesomeness" + numChaos);
        ChaosPanel.setSize(600, 600);
        ChaosPanel.setContentPane(panel);
     
        ChaosPanel.setVisible(true);
    }
}//GEN-LAST:event_GenerateActionPerformed

private void ChangeVerticesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeVerticesActionPerformed
    
            String delims = "[ ]+";
            String SNumVertices = JOptionPane.showInputDialog(null, "How many vertices?");
            try{
                numVertices = Integer.parseInt(SNumVertices);
            }catch(java.lang.NumberFormatException e){
                
                ErrorLabel.setText("Not a number, you poop!");
                JOptionPane.showMessageDialog(this,"Not a number, you poop! Java says \n" + e, "Not a number!", 0);
                
            }
            
            String SVertices = JOptionPane.showInputDialog(null, "Enter vertices like so: x1 y1 x2 y2 for as many vertices as you specified in the previous dialog. ");
            
            String[] coordinates =  SVertices.split(delims);
            boolean tooLong = false;
            boolean notANumber = false;
            for (int i = 0; i < numVertices; i++){
                //System.out.println(coordinates[2*i] + " " + coordinates[(2*i)+1]);
                try{
                    vY[i] = Double.parseDouble(coordinates[(2*i)+1]);
                    vX[i] = Double.parseDouble(coordinates[2*i]);
                }catch(java.lang.NumberFormatException e){
                    if(notANumber == false){
                        ErrorLabel.setText("Not a number, you poop!");
                        JOptionPane.showMessageDialog(this,"Not a number, you poop! Java says \n" + e, "Not a number!", i);
                        notANumber = true;
                    }
                }catch(java.lang.ArrayIndexOutOfBoundsException f){
                    if(tooLong == false){    
                        ErrorLabel.setText("Too long, you poop!");
                        JOptionPane.showMessageDialog(this,"Too long, you poop! Java says \n" + f, "Too long!", i);
                        tooLong = true;
                    }
                }
                
            
            }
            
        
        
}//GEN-LAST:event_ChangeVerticesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaosGui3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaosGui3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaosGui3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaosGui3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ChaosGui3 a =new ChaosGui3();
                a.setVisible(true);
                //a.add(Generator.generate(, ERROR, ERROR, WIDTH, WIDTH, vX, vY, numVertices))
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeVertices;
    private javax.swing.JTextField Denom;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton Generate;
    private javax.swing.JTextField Maxpoints;
    private javax.swing.JTextField Numer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField seedx;
    private javax.swing.JTextField seedy;
    // End of variables declaration//GEN-END:variables
}
